name = "ErisModpack"
author = "Menma736-wh0islalexzero"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2629d0c1f904120099b3d61dd468ac5cc3e00d170e58a2abd7d00f522c26af15"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
