name = "ErisModpack"
author = "Menma736-wh0isalexzero"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8727220fab9a39ddb1b4b672d0591d577dae50fd6d7a3d0cfd8949b57b9e72d0"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
