name = "Eris"
author = "Menma736-Wh0isalexzero"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36294e8ccd14f9ba16a2136de93d1cc28e2290495a255e1c6a499c4ca6d9f602"

[versions]
forge = "47.0.0"
minecraft = "1.20.1"
