
#MixEnergy Configuration
[general]
	#Starting value of maximum energy for players
	#Range: 1.0 ~ 1000.0
	defaultMaxEnergy = 45.0
	#Whether energy is spent on breaking and placing blocks (true - yes, false - no)
	energyCostForBreakingBlocks = true
	#Whether energy is spent on attacks (true - yes, false - no)
	energyCostForAttacks = true
	#Energy recovery delay time after action (in milliseconds)
	#Range: 0 ~ 10000
	energyRegenCooldown = 1500

